=== Nik256/PracticeXML/src/main/resources/goods.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->

<xs:complexType name="good">
	<xs:sequence>
		<xs:element name="manufacturer" type="xs:string"/>
		<xs:element name="model" type="xs:string"/>
		<xs:element name="date" type="xs:date"/>
		<xs:element name="color" type="xs:string"/>
		<xs:element name="amount" type="xs:string"/>
	</xs:sequence>
	<xs:attribute name="id" type="xs:string" use="required"/>
</xs:complexType>

<xs:element name="goods">
	<xs:complexType>
		<xs:sequence>
			
			<xs:element name="food">
				<xs:complexType>
					<xs:sequence>
						
						<xs:element name="cake">
							<xs:element ref="good"/>
						</xs:element>
						
						<xs:element name="candy">
							<xs:element name="good" type="good"/>
						</xs:element>
						
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="clothes">
				<xs:complexType>
					<xs:sequence>
						
						<xs:element name="coat">
							<xs:element name="good" type="good"/>
						</xs:element>
						
						<xs:element name="t-shirt">
							<xs:element name="good" type="good"/>
						</xs:element>
						
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="furniture">
				<xs:complexType>
					<xs:sequence>
						
						<xs:element name="table">
							<xs:element name="good" type="good"/>
						</xs:element>
						
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Nik256/PracticeXML/src/main/resources/goods.xml
<?xml version="1.0" encoding="UTF-8"?>
<goods xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation='goods.xsd'>
	<food>
		<cake>
			<good id="123">
				<manufacturer>China, Hangzhou</manufacturer>
				<model>CK234</model>
				<date>12-02-2019</date>
				<color>Pink</color>
				<amount>10$, 12pcs</amount>
			</good>
			
			<good id="321">
				<manufacturer>Willy Wonka</manufacturer>
				<model>CK343</model>
				<date>12-03-2019</date>
				<color>Red</color>
				<amount>15$, 22536pcs</amount>
			</good>
		</cake>
		<candy>
			<good id="4534">
				<manufacturer>Russia, Moscow</manufacturer>
				<model>CY034</model>
				<date>04-11-2018</date>
				<color>Blue</color>
				<amount>3$, 534pcs</amount>
			</good>
		</candy>
	</food>
	
	<clothes>
		<coat>
			<good id="8567">
				<manufacturer>China, Beijing</manufacturer>
				<model>TH120</model>
				<date>12-03-2004</date>
				<color>Green</color>
				<amount>100$, 26pcs</amount>
			</good>
		</coat>
		<t-shirt>
			<good id="7765">
				<manufacturer>Russia, Saint Petersburg</manufacturer>
				<model>HJ943</model>
				<date>16-11-2016</date>
				<color>White</color>
				<amount>5$, 1024pcs</amount>
			</good>
		</t-shirt>
	</clothes>
	
	<furniture>
		<table>
			<good id="44534">
				<manufacturer>Russia, Izhevsk</manufacturer>
				<model>FN032</model>
				<date>23-07-2013</date>
				<color>Brown</color>
				<amount>0</amount>
			</good>
		</table>
	</furniture>
</goods>
